export const ADD_SEQUENCE = "ADD_SEQUENCE";
export const SET_CURRENT_SEQUENCE = "SET_CURRENT_SEQUENCE";
export const ADD_STEP_TO_CURRENT_SEQUENCE = "ADD_STEP_TO_CURRENT_SEQUENCE";
export const FETCH_LOCAL_STORAGE = "FETCH_LOCAL_STORAGE";
export const CLEAR_CURRENT_SEQUENCE = "CLEAR_CURRENT_SEQUENCE";
export const SEQUENCE_FINISHED_PLAYING = "SEQUENCE_FINISHED_PLAYING";
export const SEQUENCE_STARTED_PLAYING = "SEQUENCE_STARTED_PLAYING";
